version: "3.7"
services:
  mariadb:
    image: mariadb
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: "thepasswordyouwanttoaccessthedatabase"
      MARIADB_DATABASE: "test"
      MARIADB_USER: "test"
      MARIADB_PASSWORD: "123456"

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "127.0.0.1:9100:80"
    environment:
      - PMA_HOST=mariadb
    depends_on:
      - "mariadb"
